### PR TITLE
add array#includes method and tests

### PR DESCRIPTION
**Pull request by nicknisi**
This PR adds an Array includes method implementation and tests.

### CODE REVIEW

**Comment by kitsonk** [comment]
Why no offloading to native?

**Comment by kfranqueiro** [comment]
@kitsonk you could ask the same of all of the other functions in `array.ts`.

I suspect that originally the answer to this question was because we originally proposed also having the option of hooking these methods up as polyfills, but we eventually [put the brakes on that idea](https://docs.google.com/document/d/1E_nh2Cq0E6LJCXPvL2mbPujrpyBIXSXTr2epwlPVABU/edit#heading=h.hx1cbuyjakf4).

Either way, this PR is currently consistent with everything else in `array.ts` - the question of whether to defer to native when present is probably a larger separate question.

**Comment by nicknisi** [comment]
Yeah, I kept it consistent with the other methods in this file, but would be happy to add native offloading to these methods.

**Comment by kitsonk** [comment]
Well since this matches existing, lets just merge it and open up another issue to do native offloading (#114)

**Comment by kitsonk** [comment]
:+1: from me

**Comment by nicknisi** [comment]
Merged via e97df09

**Pull request merged**
