### PR TITLE
Removing streams and importing from dojo-streams, issue #225

### PR DESCRIPTION
**Pull request by rorticus**
Moving streams into a separate package,

https://github.com/rorticus/streams

I'm not really sure how to make `rorticus/streams` into `dojo/streams` but I'm guessing someone smart can tell me!

### CODE REVIEW

**Review by dylans — APPROVED** [review]
This is fine as a first pass, though I believe we were hoping to also refactor request/node.ts to not depend on streams so that this package wouldn't just pull in streams as a dependency. That said, we can do that refactoring/rework after we land this patch (which just moves streams into a separate package).

**Comment by dylans** [comment]
> I'm not really sure how to make rorticus/streams into dojo/streams but I'm guessing someone smart can tell me!

Basically someone with admin in both accounts can move a repo, and then you can refork it once it has been moved.

**Comment by rorticus** [comment]
> I believe we were hoping to also refactor request/node.ts to not depend on streams

I can try that! Would that be using observables instead?

**Comment by dylans** [comment]
> Would that be using observables instead?

I'm not sure I know the right answer to that. To be fair, streams within Node.js usage is probably a good thing, but it feels wrong for all of core to rely on streams with the only dependency being the Node.js request API. Perhaps take a look at how it's being used and make a suggestion?

**Comment by rorticus** [comment]
OK, so... it looks like it's _not_ being used... I [did a search](https://github.com/search?utf8=%E2%9C%93&q=org%3Adojo+user%3Adojo+streamTarget+in%3Afile&type=Code&ref=searchresults) for `streamTarget` (the name of the option that gets passed to a node request to use a stream)  on all the `dojo` repositories and the only hits are in the node request file...

**Comment by dylans** [comment]
Right, the only thing that would eventually use it would be a Node.js request (which was to be supported for crypto and io, which have been deferred as we've not been focusing on Node.js APIs, though we want what we have to work inside Node.js... hopefully that distinction makes sense).

**Pull request merged**
