### PR TITLE
Remove global and use @dojo/shim/global

### LINKED ISSUE #302: Remove global in lieu of shim/global
**Enhancement**

Global should be removed in lieu of shim/global.  See dojo/shim#61.

### PR DESCRIPTION
**Pull request by kitsonk**
**Type:** bug

The following has been addressed in the PR:

* [X] There is a related issue
* [X] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [X] Unit or Functional tests are included in the PR

**Description:**

Removes global from core and uses `@dojo/shim/global` instead.

Resolves #302

### CODE REVIEW

**Comment by kitsonk** [comment]
Requires dojo/shim#80 to land first.

**Review by dylans — APPROVED** [review]

**Comment by kitsonk** [comment]
Let's re-export `@dojo/shim/global` for now to cause the least amount of downstream breakage.

**Review by dylans — APPROVED** [review]

**Comment by dylans** [comment]
This one is now stale and needs a rebase @kitsonk

**Comment by kitsonk** [comment]
Replaced with a different PR

**Pull request closed without merging**
