### PR TITLE
Clean up `has` module.

### PR DESCRIPTION
**Pull request by lzhoucs**
It is good to have all `has` detection defined in one place for internal use. It is a minor refactoring.

### CODE REVIEW

**Review by dylans — CHANGES_REQUESTED** [review]
We should land this... has a conflict and needs a rebase.

**Comment by lzhoucs** [comment]
I did a rebase. The new Codecov is being slightly confusing. I don't see how my change will decrease coverage. :)

Update: it turns out the Codecov data was out dated after I rebased it. The [latest info](https://github.com/dojo/core/pull/263#issuecomment-276572795) is correct.

**Review by dylans — APPROVED** [review]

**Comment by dylans** [comment]
@lzhoucs go ahead and land it, thanks!

**Comment by lzhoucs** [comment]
@dylans , I don't think I have permission yet...

**Pull request merged**
