### PR TITLE
POST body with request/node

### PR DESCRIPTION
**Pull request by sebilasse**
see https://github.com/dojo/core/issues/197

### CODE REVIEW

**Comment by kitsonk** [comment]
@sebilasse thanks for the contribution.  The PR looks fine, but it would be great to get tests for it before we were to merge it.

**Comment by sebilasse** [comment]
What would a test look like without a server?

What I also stumbled upon is the note in `request/node`:
"TODO: This redirect code is not 100% correct according to the RFC; needs to handle redirect loops and restrict/modify certain redirects"
This feels pretty important and could also be a (trackable) issue (especially because redirect loops will occur, try german lead media site "spiegel.de" [without 'www.']).

**Comment by kitsonk** [comment]
There is a server integrated into the test harness.  The server code is located in `tests/services/echo.ts` and is bootstrapped when the tests are run.

**Comment by rorticus** [comment]
Closing because issue was closed.

**Pull request closed without merging**
